<?php
echo '<!DOCTYPE html>';
echo '<html style="font-size: 16px;" lang="en"><head>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta charset="utf-8">';
echo '<meta name="keywords" content="KRYO TE​​CH">';
echo '<meta name="description" content="">';
echo '<title>Home</title>';
echo '<link rel="stylesheet" href="nicepage.css" media="screen">';
echo '<link rel="stylesheet" href="Home.css" media="screen">';
echo '<script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>';
echo '<script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>';
echo '<meta name="generator" content="Nicepage 4.21.12, nicepage.com">';
echo '<link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">';
echo '<link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">';
echo '';
echo '';
echo '';
echo '';
echo '<script type="application/ld+json">{';
echo '"@context": "http://schema.org",';
echo '"@type": "Organization",';
echo '"name": "",';
echo '"logo": "images/image8.png",';
echo '"sameAs": [';
echo '"https://facebook.com/name",';
echo '"https://twitter.com/name",';
echo '"https://www.instagram.com/name"';
echo ']';
echo '}</script>';
echo '<meta name="theme-color" content="#478ac9">';
echo '<meta name="twitter:site" content="@">';
echo '<meta name="twitter:card" content="summary_large_image">';
echo '<meta name="twitter:title" content="Home">';
echo '<meta name="twitter:description" content="">';
echo '<meta property="og:title" content="Home">';
echo '<meta property="og:type" content="website">';
echo '</head>';
echo '<body class="u-body u-overlap u-overlap-contrast u-stick-footer u-xl-mode" data-lang="en"><header class="u-align-left u-clearfix u-header u-section-row-container" id="sec-7df0"><div class="u-section-rows">';
echo '<div class="u-grey-70 u-section-row u-section-row-1" id="sec-46aa">';
echo '<div class="u-clearfix u-sheet u-sheet-1">';
echo '<div class="u-social-icons u-spacing-10 u-social-icons-1">';
echo '<a class="u-social-url" title="facebook" target="_blank" href="https://facebook.com/name"><span class="u-icon u-social-facebook u-social-icon u-icon-1"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-831d"></use></svg><svg class="u-svg-content" viewBox="0 0 112 112" x="0" y="0" id="svg-831d"><circle fill="currentColor" cx="56.1" cy="56.1" r="55"></circle><path fill="#FFFFFF" d="M73.5,31.6h-9.1c-1.4,0-3.6,0.8-3.6,3.9v8.5h12.6L72,58.3H60.8v40.8H43.9V58.3h-8V43.9h8v-9.2';
echo 'c0-6.7,3.1-17,17-17h12.5v13.9H73.5z"></path></svg></span>';
echo '</a>';
echo '<a class="u-social-url" title="twitter" target="_blank" href="https://twitter.com/name"><span class="u-icon u-social-icon u-social-twitter u-icon-2"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-420f"></use></svg><svg class="u-svg-content" viewBox="0 0 112 112" x="0" y="0" id="svg-420f"><circle fill="currentColor" class="st0" cx="56.1" cy="56.1" r="55"></circle><path fill="#FFFFFF" d="M83.8,47.3c0,0.6,0,1.2,0,1.7c0,17.7-13.5,38.2-38.2,38.2C38,87.2,31,85,25,81.2c1,0.1,2.1,0.2,3.2,0.2';
echo 'c6.3,0,12.1-2.1,16.7-5.7c-5.9-0.1-10.8-4-12.5-9.3c0.8,0.2,1.7,0.2,2.5,0.2c1.2,0,2.4-0.2,3.5-0.5c-6.1-1.2-10.8-6.7-10.8-13.1';
echo 'c0-0.1,0-0.1,0-0.2c1.8,1,3.9,1.6,6.1,1.7c-3.6-2.4-6-6.5-6-11.2c0-2.5,0.7-4.8,1.8-6.7c6.6,8.1,16.5,13.5,27.6,14';
echo 'c-0.2-1-0.3-2-0.3-3.1c0-7.4,6-13.4,13.4-13.4c3.9,0,7.3,1.6,9.8,4.2c3.1-0.6,5.9-1.7,8.5-3.3c-1,3.1-3.1,5.8-5.9,7.4';
echo 'c2.7-0.3,5.3-1,7.7-2.1C88.7,43,86.4,45.4,83.8,47.3z"></path></svg></span>';
echo '</a>';
echo '<a class="u-social-url" title="instagram" target="_blank" href="https://www.instagram.com/name"><span class="u-icon u-social-icon u-social-instagram u-icon-3"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-580e"></use></svg><svg class="u-svg-content" viewBox="0 0 112 112" x="0" y="0" id="svg-580e"><circle fill="currentColor" cx="56.1" cy="56.1" r="55"></circle><path fill="#FFFFFF" d="M55.9,38.2c-9.9,0-17.9,8-17.9,17.9C38,66,46,74,55.9,74c9.9,0,17.9-8,17.9-17.9C73.8,46.2,65.8,38.2,55.9,38.2';
echo 'z M55.9,66.4c-5.7,0-10.3-4.6-10.3-10.3c-0.1-5.7,4.6-10.3,10.3-10.3c5.7,0,10.3,4.6,10.3,10.3C66.2,61.8,61.6,66.4,55.9,66.4z"></path><path fill="#FFFFFF" d="M74.3,33.5c-2.3,0-4.2,1.9-4.2,4.2s1.9,4.2,4.2,4.2s4.2-1.9,4.2-4.2S76.6,33.5,74.3,33.5z"></path><path fill="#FFFFFF" d="M73.1,21.3H38.6c-9.7,0-17.5,7.9-17.5,17.5v34.5c0,9.7,7.9,17.6,17.5,17.6h34.5c9.7,0,17.5-7.9,17.5-17.5V38.8';
echo 'C90.6,29.1,82.7,21.3,73.1,21.3z M83,73.3c0,5.5-4.5,9.9-9.9,9.9H38.6c-5.5,0-9.9-4.5-9.9-9.9V38.8c0-5.5,4.5-9.9,9.9-9.9h34.5';
echo 'c5.5,0,9.9,4.5,9.9,9.9V73.3z"></path></svg></span>';
echo '</a>';
echo '</div>';
echo '<nav data-position="" class="u-menu u-menu-one-level u-offcanvas u-menu-1">';
echo '<div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700;">';
echo '<a class="u-button-style u-custom-active-border-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link" href="#" style="padding: 2px 0px; font-size: calc(1em + 4px);">';
echo '<svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>';
echo '<svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>';
echo '</g></svg>';
echo '</a>';
echo '</div>';
echo '<div class="u-custom-menu u-nav-container">';
echo '<ul class="u-nav u-spacing-2 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-active-grey-5 u-button-style u-hover-grey-10 u-nav-link u-text-active-grey-90 u-text-hover-grey-90" href="#" style="padding: 10px 24px;">Page:</a>';
echo '</li><li class="u-nav-item"><a class="u-active-grey-5 u-button-style u-hover-grey-10 u-nav-link u-text-active-grey-90 u-text-hover-grey-90" href="#" style="padding: 10px 24px;">Homepage</a>';
echo '</li></ul>';
echo '</div>';
echo '<div class="u-custom-menu u-nav-container-collapse">';
echo '<div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">';
echo '<div class="u-inner-container-layout u-sidenav-overflow">';
echo '<div class="u-menu-close"></div>';
echo '<ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="#">Page:</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="#">Homepage</a>';
echo '</li></ul>';
echo '</div>';
echo '</div>';
echo '<div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</div>';
echo '<div class="u-border-2 u-border-custom-color-1 u-section-row u-section-row-2" id="sec-37e8">';
echo '<div class="u-clearfix u-sheet u-sheet-2">';
echo '<img class="u-expanded-height u-image u-image-1" src="images/image9.png" data-image-width="311" data-image-height="417">';
echo '<h1 class="u-align-center u-custom-font u-font-montserrat u-text u-text-custom-color-1 u-text-default u-title u-text-1">KRYO TE​​CH</h1>';
echo '<img class="u-image u-image-default u-preserve-proportions u-image-2" src="images/image8.png" alt="" data-image-width="166" data-image-height="151">';
echo '<a href="https://nicepage.com/c/art-design-website-templates" class="u-image u-logo u-image-3" data-image-width="166" data-image-height="151">';
echo '<img src="images/image8.png" class="u-logo-image u-logo-image-1">';
echo '</a>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</div>';
echo '</div></header>';
echo '<section class="u-clearfix u-custom-color-2 u-section-1" id="sec-a384">';
echo '<div class="u-clearfix u-sheet u-sheet-1"></div>';
echo '</section>';
echo '<section class="u-align-center u-clearfix u-container-align-center-xs u-custom-color-2 u-section-2" id="carousel_1c4c">';
echo '<div class="u-clearfix u-sheet u-sheet-1">';
echo '<div class="u-list u-list-1">';
echo '<div class="u-repeater u-repeater-1">';
echo '<div class="u-align-center u-border-5 u-border-custom-color-1 u-container-style u-custom-color-3 u-custom-item u-list-item u-repeater-item u-shape-rectangle u-list-item-1" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-1">';
echo '<h4 class="u-text u-text-1">TEMPERATURE</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-align-center u-border-5 u-border-custom-color-1 u-container-style u-custom-color-3 u-custom-item u-list-item u-repeater-item u-shape-rectangle u-list-item-2" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-2">';
echo '<h4 class="u-text u-text-2">HUMIDITY</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-align-center u-border-5 u-border-custom-color-1 u-container-style u-custom-color-3 u-custom-item u-list-item u-repeater-item u-shape-rectangle u-list-item-3" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-3">';
echo '<h4 class="u-text u-text-3">WEIGHT</h4>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '</section>';
echo '<section class="u-align-center u-clearfix u-container-align-center-xs u-custom-color-2 u-section-3" id="carousel_be0a">';
echo '<div class="u-clearfix u-sheet u-valign-middle u-sheet-1">';
echo '<div class="u-list u-list-1">';
echo '<div class="u-repeater u-repeater-1">';
echo '<div class="u-align-center u-border-5 u-border-custom-color-1 u-container-style u-custom-color-3 u-list-item u-repeater-item u-shape-rectangle u-list-item-1" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-1">';
echo '<h4 class="u-align-center u-text u-text-1">POWER</h4>';
echo '</div>';
echo '</div>';
echo '<div class="u-align-center u-border-5 u-border-custom-color-1 u-container-align-center u-container-style u-custom-color-3 u-list-item u-repeater-item u-shape-rectangle u-list-item-2" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">';
echo '<div class="u-container-layout u-similar-container u-valign-top u-container-layout-2">';
echo '<h4 class="u-align-center u-text u-text-2">GAS</h4>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</section>';
echo '<style class="u-overlap-style">.u-overlap:not(.u-sticky-scroll) .u-header {';
echo 'background-color: #7d2ae8 !important; background-image: linear-gradient(#808080, #7d2ae8) !important';
echo '}</style>';
echo '';
echo '';
echo '<footer class="u-align-center u-border-4 u-border-custom-color-1 u-clearfix u-footer u-grey-70 u-footer" id="sec-4409"><div class="u-clearfix u-sheet u-sheet-1">';
echo '<p class="u-small-text u-text u-text-variant u-text-1">For more details:</p>';
echo '<img class="u-image u-image-default u-preserve-proportions u-image-1" src="images/image5.png" alt="" data-image-width="225" data-image-height="225">';
echo '<img class="u-image u-image-default u-preserve-proportions u-image-2" src="images/image4.png" alt="" data-image-width="225" data-image-height="225">';
echo '<nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">';
echo '<div class="menu-collapse">';
echo '<a class="u-button-style u-nav-link" href="#">';
echo '<svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-cd6b"></use></svg>';
echo '<svg class="u-svg-content" version="1.1" id="svg-cd6b" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>';
echo '</g></svg>';
echo '</a>';
echo '</div>';
echo '<div class="u-custom-menu u-nav-container">';
echo '<ul class="u-nav u-unstyled"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Home.html" style="padding: 10px 48px;">Home</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="About-Us.html" style="padding: 10px 48px;">About Us</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Contact-Us.html" style="padding: 10px 48px;">Contact Us</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 48px;">Privacy Policy</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 48px;">Terms</a>';
echo '</li></ul>';
echo '</div>';
echo '<div class="u-custom-menu u-nav-container-collapse">';
echo '<div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">';
echo '<div class="u-inner-container-layout u-sidenav-overflow">';
echo '<div class="u-menu-close"></div>';
echo '<ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Home.html">Home</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="About-Us.html">About Us</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Contact-Us.html">Contact Us</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link">Privacy Policy</a>';
echo '</li><li class="u-nav-item"><a class="u-button-style u-nav-link">Terms</a>';
echo '</li></ul>';
echo '</div>';
echo '</div>';
echo '<div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>';
echo '</div>';
echo '</nav>';
echo '<img class="u-image u-image-contain u-image-default u-preserve-proportions u-image-3" src="images/image.png" alt="" data-image-width="320" data-image-height="320">';
echo '<img class="u-image u-image-default u-preserve-proportions u-image-4" src="images/image2.png" alt="" data-image-width="214" data-image-height="236">';
echo '<img class="u-image u-image-default u-preserve-proportions u-image-5" src="images/image6.png" alt="" data-image-width="225" data-image-height="225">';
echo '</div></footer>';
echo '';
echo '';
echo '</body></html>';
?>